version: '3.8'

services:
  redis:
    image: redis:latest

  sync-data:
    build:
      context: .
      dockerfile: ./sync-data/Dockerfile
    volumes:
      - ./sync-data:/var/www/html
      - /var/www/html/vendor
      - ./sync-data/storage:/var/www/html/storage
    ports:
      - 8000:8000
    environment:
      - QUEUE_CONNECTION=${QUEUE_CONNECTION}
      - REDIS_HOST=${REDIS_HOST}
      - CRUD_API=${CRUD_API}
      - REDIS_CLIENT=${REDIS_CLIENT}
      - BATCH_SIZE=${BATCH_SIZE}

  # api:
  #   image: yiisoftware/yii2-php:7.4-apache
  #   volumes:
  #     # - ~/.composer-docker/cache:/root/.composer/cache:delegated
  #     - ./api:/app:delegated
  #   ports:

  api:
    build:      
      context: .
      dockerfile: ./api/Dockerfile
    volumes:
      - ./api:/var/www/html
      - /var/www/html/vendor
    ports:
      - 8080:8080
